name: Ensure Patched Templates

on:
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install uv
      uses: astral-sh/setup-uv@v1
      with:
        version: latest
        
    - name: Install dependencies
      run: |
        uv pip install pytest ruamel.yaml
        
    - name: Test patch_templates target
      run: |
        make patch_templates

        if [ -n "$(git status --porcelain)" ]; then
          echo "Error: Running patch_templates produced changes. Please run 'make patch_templates' locally and commit the changes."
          echo "git status"
          git status
          echo "git diff"
          git diff
          exit 1
        fi
