name: Run Tests

on:
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install uv
      uses: astral-sh/setup-uv@v1
      with:
        version: latest
        python-version: '3.11'
        
    - name: Ensure Docker Compose is installed
      run: docker compose --version
        
    - name: Run tests
      run: make tests
